.TH LMPD 7 "2 August 2011" "" ""
.SH NAME
lmpd \- Lightweight Modular Policy Daemon for Postfix.

.SH DESCRIPTION
This daemon is intended to make user whitelisting 
for Postfix using SMTP_ACCESS_POLICY. Whitelisting 
is implemented by means of Postfix aliases and MySQL
database.

The LMPD database can be trained (automatically 
updated) by the Dovecot server. For this, you have to 
install a patched version of Dovecot antispam plugin.

.SH CONFIGURATION

Here you can see the runtime options of LMPD
(they are displayed with default values):

.nf
# MySQL connection options
mysql:
  host: 127.0.0.1
  port: 3306
  user: mail
  password: mail
  dbname: mail
  # Limit of MySQL connections
  pool: 10 

# Daemon's UID and GID
system:
  user: postfix
  group: postfix 

# Network settings
network:
  # Network type: unix or tcp
  type: unix
  # for "unix": path to unix domain socket
  socket: /tmp/lmpd.sock
  # for "tcp": IP address to bind
  address: 127.0.0.1
  # for "tcp": TCP port to bind
  port: 7000
 
filters:
  # Names of policies
  order:
    - AddressPolicy
    - DomainPolicy
    - UserPolicy
  # Default answer in policies
  default: DUNNO
.fi

.SH AUTHOR

Nikolay Bogdanov <nikolay.bogdanov@flant.ru>
