#Зададим MySQL базу и таблицу в ней
mysql:
  host: 127.0.0.1
  port: 3306
  user: postfix
  password: 5xMZosHi
  dbname: mail
  pool: 10

system:
  user: postfix
  group: 

network:
  type: unix
  socket: /home/gyrt/DEV-Code/policyd/policy.sock

filters:
  order:
    - AddressPolicy
    - DomainPolicy
    - UserPolicy
  default: DUNNO
