#Зададим MySQL базу и таблицу в ней
mysql:
  host: 192.168.0.2
  port: 3306
  user: postfix
  password: XUCqVRdE6EZRnrS5
  dbname: postfix
  retry_count: 3

system:
  user: gyrt
  group: gyrt

socket:
  socket: /home/gyrt/DEV-Code/policyd/policy.sock

filters:
  order:
    - AddressPolicy
    - DomainPolicy
    - UserPolicy
  default: DUNNO
