#Зададим MySQL базу и таблицу в ней
mysql:
  host: 172.27.1.2
  port: 3306
  user: mail_ext
  password: prevedpochta
  dbname: mail_ext
  pool: 10

system:
  user: gyrt
  group: gyrt

network:
  type: unix
  socket: /home/gyrt/DEV-Code/policyd/policy.sock

filters:
  order:
    - AddressPolicy
    - DomainPolicy
    - UserPolicy
  default: DUNNO
