.TH TF_POLICYD 7 "2 August 2011" "" ""
.SH NAME
tf_policyd \- The postfix python whitelisting daemon.

.SH DESCRIPTION
This daemon was created to do easy user whitelisting
for Postfix, using SMTP_ACCESS_POLICY. It use postfix
aliases and MySQL database for whitelisting.

You can train your daemon using dovecot. If you want this 
fucntion - install patched dovecot-antispam.

.SH CONFIGURATION

You have the following run-time options (shown along with the default):

.nf
#MySQL connaction options
mysql:
  host: 127.0.0.1
  port: 3306
  user: mail
  password: mail
  dbname: mail
  # Limit of mysql connections
  pool: 10 

# Daemon uid and gid
system:
  user: postfix
  group: postfix 

# Network settings
network:
  # Network type. unix or tcp
  type: unix
  # Path to unix domain socket if network type "unix"
  socket: /home/gyrt/DEV-Code/policyd/policy.sock
  # IP address to bind if network type "tcp"
  address: 127.0.0.1
  # TCP port to bind if network type "tcp"
  port: 7000
 
filters:
  # Names of policitcs
  order:
    - AddressPolicy
    - DomainPolicy
    - UserPolicy
  # Default answer in politics
  default: DUNNO
.fi

.SH AUTHORS

Nikolay Bogdanov
